# CREATE TABLE CINE.MOVIE
# (
#     ID       INT NOT NULL AUTO_INCREMENT,
#     TITLE    VARCHAR(60),
#     DIRECTOR VARCHAR(60),
#     RATING   INT,
#     CONSTRAINT USER_ID_PK PRIMARY KEY (ID)
# );
INSERT INTO CINE.MOVIE (ID, TITLE, DIRECTOR, RATING)
VALUES (1, 'THOR', 'NO SE', 98);